theme: null
title: Save Your Code
description: A site about saving your code with Git and GitHub
baseurl: "" # leave empty for root
url: "https://saveyourcode.dev"
markdown: kramdown
author:
  name: Dave Cross
  url: https://davecross.co.uk/

logo: /assets/images/saveyourcode.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

ga4: G-SF6ZXD1B95

twitter:
  username: NooneUsesTwitter

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/saveyourcode.png

