theme: null
title: Save Your Code
description: A site about saving your code with Git and GitHub
baseurl: "" # leave empty for root
url: "https://saveyourcode.dev"
markdown: kramdown
author: Dave Cross

og_image: /assets/images/saveyourcode.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag

ga4: G-SF6ZXD1B95

